product: bascontrol22d4
full_name: Contemporary Controls BAScontrol22D 4
type: product

benchmark_id: BASCONTROL22D-4
benchmark_root: "./guide"

components_root: "../../components"

profiles_root: "./profiles"

cpes_root: "./cpes"
cpes:
  - bascontrol22d4:
      name: "cpe:/a:contemporarycontrols:bascontrol22d:4"
      title: "Contemporary Controls BAScontrol22D 4"
      check_id: installed_app_is_bascontrol22d4
